# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='')),
                ('address', models.TextField(default='/home/eugene/Desktop/django/mysite/media')),
            ],
        ),
    ]
